name: recipe-manager # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Manages your recipes. # 79 char long summary
description: |
  Manages recipes.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
    recipe-manager:
        command: ./bin/gooseberry-recipe-manager-heroku
        daemon: simple
        plugs:
            - network
            - network-bind

parts:
  recipe-manager:
    plugin: go
    source: . #https://github.com/evanlinjin/gooseberry-recipe-manager-heroku.git
    prime:
        - bin/gooseberry-recipe-manager-heroku
